// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl2EEplr-Cs5f5oiglfetLNQkwLlEBzaY',
    appId: '1:1016646892735:web:b1bf49116a170d7fd51a0a',
    messagingSenderId: '1016646892735',
    projectId: 'applearnjava',
    authDomain: 'applearnjava.firebaseapp.com',
    storageBucket: 'applearnjava.firebasestorage.app',
    measurementId: 'G-NWSWJPSG45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJRTN34EWL3jxr5ukmTeb-fNGIG1V710',
    appId: '1:377464465984:android:9a6fcb5facc47dfa5b0da5',
    messagingSenderId: '377464465984',
    projectId: 'applea-e4729',
    storageBucket: 'applea-e4729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBkRk1y3JtLAEOJHuwLJ-R36cXutKpKI',
    appId: '1:377464465984:ios:b58f74f848bb1a955b0da5',
    messagingSenderId: '377464465984',
    projectId: 'applea-e4729',
    storageBucket: 'applea-e4729.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBkRk1y3JtLAEOJHuwLJ-R36cXutKpKI',
    appId: '1:377464465984:ios:b58f74f848bb1a955b0da5',
    messagingSenderId: '377464465984',
    projectId: 'applea-e4729',
    storageBucket: 'applea-e4729.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl2EEplr-Cs5f5oiglfetLNQkwLlEBzaY',
    appId: '1:1016646892735:web:a712a01175d43ab5d51a0a',
    messagingSenderId: '1016646892735',
    projectId: 'applearnjava',
    authDomain: 'applearnjava.firebaseapp.com',
    storageBucket: 'applearnjava.firebasestorage.app',
    measurementId: 'G-D2FHTR223X',
  );

}